import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Grid from '@mui/material/Grid'
import Head from 'next/head'

const Developer = ()=>{
    return (
        <div>
            <Head>
                <title>Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Grid container justifyContent="space-around">
                <Grid item xs={10} md={8}>
                    <h3 style={{textAlign: 'center', marginBottom: '40px'}}>This App Was Developed Entirely By <b style={{fontSize: '1.2em', color: '#1976D2', cursor: 'pointer'}} onClick={()=>{window.open('https://www.linkedin.com/in/amer-sulaiman/')}}>Amer Sulaiman</b></h3>
                    <pre>
                        <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>The Used Techstack:</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;- React.js/Next.js (For the frontend). 
                        <br />
                        &nbsp;&nbsp;&nbsp;&nbsp;- Flask (For the backend and the API).


                        <p style={{fontSize: '1.2em', fontWeight: 'bold'}}>What Does this website do?</p>
                        &nbsp;&nbsp;&nbsp;&nbsp;You can check if your domain is blacklisted. A blacklisted domain can lead to many problems, including sent emails landing in the spam folder or even bouncing.
                    </pre>
                    

                </Grid>
            </Grid>
            
        </div>
    )
}

export default Developer;